<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Ajouter Produits</h1>

    <form action="" method="POST">
        <div>
            <label for="title">Titre :</label>
            <input type="text" name="title" id="title" value="">
        </div>
        <div>
            <label for="image">Image :</label>
            <input type="text" name="image" id="image" value="">
        </div>
        <div>
            <label for="description">Description :</label>
            <textarea name="description" id="description"></textarea>
        </div>
        <div>  
            <label for="quantity">Quantité :</label>  
            <input type="text" name="quantity" id="quantity" value="">
        </div>
        <div>
            <label for="price">Prix :</label>
            <input type="text" name="price" id="price" value="">
        </div>  
        <div>
            <select name="category" id="category">
                <?php foreach($categorys as $category):?>
                    <option value="<?=$category->getIdCategory();?>"><?=$category->getName();?></option>   
                <?php endforeach ?> 
            </select> 
        </div>  
        <input type="submit" name="submit" value="Ajouter">
    </form>
</body>
</html>
