<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="<?=constructUrl('/editAdmin', ['id' => $product->getIdProduct()])?>" method="POST">
        <input type="text" name="title" value="<?=$product->getTitle();?>"><br>
        <input type="text" name="image" value="<?=$product->getImage();?>"><br>
        <textarea name="description"><?=$product->getDescription();?></textarea><br>
        <input type="text" name="quantity" value="<?=$product->getQuantity();?>"><br>
        <input type="text" name="price" value="<?=$product->getPrice();?>"><br>
        <input type="submit" name="submit" value="Modifier">
    </form>
</body>
</html>