<section>
    <form action="<?=constructUrl('/editPassword',)?>" method="POST">
            <h2>Modifier mon mot de passe</h2>
            <div>
                <label for="currentPassword">Ancien mot de passe</label>
                <input type="text" name="currentPassword" id="currentPassword">
                <?php if(isset($error["currentPassword"])) : ?>
                    <p class="errors"><?=$errors["currentPassword"];?></p>
                <?php endif; ?>
            </div>

            <div>
                <label for="newPassword">Nouveau mot de passe</label>
                <input type="text" name="newPassword" id="newPassword">
            </div>  
            
            <div>
                <label for="ConfirmTheNewPassword">Confirmer le mot de passe</label>
                <input type="text" name="ConfirmTheNewPassword" id="ConfirmTheNewPassword">
                <?php if(isset($error["ConfirmTheNewPassword"])) : ?>
                    <p class="errors"> <?=$errors["ConfirmTheNewPassword"];?></p>
                <?php endif; ?>
            </div>
        </div>
        <input type="submit" name="submit" value="Modifier">
    </form>    
</section>